### ISSUE TITLE
having some issues here

### ISSUE THREAD

**Issue by CrypticKingJoe** [SkullzOS/mega.nz-account-checker#1]
Traceback (most recent call last):
  File "C:\Users\RDP\RDP\mega.nz-account-checker-main\mega.py", line 3, in <module>
    from mega import Mega
  File "C:\Users\RDP\RDP\mega.nz-account-checker-main\mega.py", line 3, in <module>
    from mega import Mega
ImportError: cannot import name 'Mega' from partially initialized module 'mega' (most likely due to a circular import) (C:\Users\RDP\RDP\mega.nz-account-checker-main\mega.py)

requirements are installed

**Comment by SkullzOS** [comment]
Check this link thttps://github.com/odwyersoftware/mega.py

Im currently working on a new python lib for mega.nz
